// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class MChat;
@class MChatIndex;
@class MChatIndex_Builder;
@class MChatList;
@class MChatList_Builder;
@class MChat_Builder;
@class MChats;
@class MChats_Builder;
@class MView;
@class MView_Builder;

@interface ZsndChatRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface MChatList : PBGeneratedMessage {
@private
  BOOL hasUnreadCnt_:1;
  int32_t unreadCnt;
  NSMutableArray* mutableChatList;
}
- (BOOL) hasUnreadCnt;
@property (readonly) int32_t unreadCnt;
- (NSArray*) chatList;
- (MChatIndex*) chatAtIndex:(int32_t) index;

+ (MChatList*) defaultInstance;
- (MChatList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MChatList_Builder*) builder;
+ (MChatList_Builder*) builder;
+ (MChatList_Builder*) builderWithPrototype:(MChatList*) prototype;

+ (MChatList*) parseFromData:(NSData*) data;
+ (MChatList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MChatList*) parseFromInputStream:(NSInputStream*) input;
+ (MChatList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MChatList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MChatList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MChatList_Builder : PBGeneratedMessage_Builder {
@private
  MChatList* result;
}

- (MChatList*) defaultInstance;

- (MChatList_Builder*) clear;
- (MChatList_Builder*) clone;

- (MChatList*) build;
- (MChatList*) buildPartial;

- (MChatList_Builder*) mergeFrom:(MChatList*) other;
- (MChatList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MChatList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) chatList;
- (MChatIndex*) chatAtIndex:(int32_t) index;
- (MChatList_Builder*) replaceChatAtIndex:(int32_t) index with:(MChatIndex*) value;
- (MChatList_Builder*) addChat:(MChatIndex*) value;
- (MChatList_Builder*) addAllChat:(NSArray*) values;
- (MChatList_Builder*) clearChatList;

- (BOOL) hasUnreadCnt;
- (int32_t) unreadCnt;
- (MChatList_Builder*) setUnreadCnt:(int32_t) value;
- (MChatList_Builder*) clearUnreadCnt;
@end

@interface MChatIndex : PBGeneratedMessage {
@private
  BOOL hasTargetHeadImg_:1;
  BOOL hasHeadImg_:1;
  BOOL hasHasNew_:1;
  BOOL hasId_:1;
  BOOL hasTargetid_:1;
  BOOL hasUserid_:1;
  BOOL hasMsg_:1;
  BOOL hasTime_:1;
  BOOL hasTopicid_:1;
  BOOL hasTopicImg_:1;
  BOOL hasTopicContent_:1;
  int32_t targetHeadImg;
  int32_t headImg;
  int32_t hasNew;
  NSString* id;
  NSString* targetid;
  NSString* userid;
  NSString* msg;
  NSString* time;
  NSString* topicid;
  NSString* topicImg;
  NSString* topicContent;
}
- (BOOL) hasId;
- (BOOL) hasTargetid;
- (BOOL) hasTargetHeadImg;
- (BOOL) hasUserid;
- (BOOL) hasHeadImg;
- (BOOL) hasHasNew;
- (BOOL) hasMsg;
- (BOOL) hasTime;
- (BOOL) hasTopicid;
- (BOOL) hasTopicImg;
- (BOOL) hasTopicContent;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* targetid;
@property (readonly) int32_t targetHeadImg;
@property (readonly, retain) NSString* userid;
@property (readonly) int32_t headImg;
@property (readonly) int32_t hasNew;
@property (readonly, retain) NSString* msg;
@property (readonly, retain) NSString* time;
@property (readonly, retain) NSString* topicid;
@property (readonly, retain) NSString* topicImg;
@property (readonly, retain) NSString* topicContent;

+ (MChatIndex*) defaultInstance;
- (MChatIndex*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MChatIndex_Builder*) builder;
+ (MChatIndex_Builder*) builder;
+ (MChatIndex_Builder*) builderWithPrototype:(MChatIndex*) prototype;

+ (MChatIndex*) parseFromData:(NSData*) data;
+ (MChatIndex*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MChatIndex*) parseFromInputStream:(NSInputStream*) input;
+ (MChatIndex*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MChatIndex*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MChatIndex*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MChatIndex_Builder : PBGeneratedMessage_Builder {
@private
  MChatIndex* result;
}

- (MChatIndex*) defaultInstance;

- (MChatIndex_Builder*) clear;
- (MChatIndex_Builder*) clone;

- (MChatIndex*) build;
- (MChatIndex*) buildPartial;

- (MChatIndex_Builder*) mergeFrom:(MChatIndex*) other;
- (MChatIndex_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MChatIndex_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (MChatIndex_Builder*) setId:(NSString*) value;
- (MChatIndex_Builder*) clearId;

- (BOOL) hasTargetid;
- (NSString*) targetid;
- (MChatIndex_Builder*) setTargetid:(NSString*) value;
- (MChatIndex_Builder*) clearTargetid;

- (BOOL) hasTargetHeadImg;
- (int32_t) targetHeadImg;
- (MChatIndex_Builder*) setTargetHeadImg:(int32_t) value;
- (MChatIndex_Builder*) clearTargetHeadImg;

- (BOOL) hasUserid;
- (NSString*) userid;
- (MChatIndex_Builder*) setUserid:(NSString*) value;
- (MChatIndex_Builder*) clearUserid;

- (BOOL) hasHeadImg;
- (int32_t) headImg;
- (MChatIndex_Builder*) setHeadImg:(int32_t) value;
- (MChatIndex_Builder*) clearHeadImg;

- (BOOL) hasHasNew;
- (int32_t) hasNew;
- (MChatIndex_Builder*) setHasNew:(int32_t) value;
- (MChatIndex_Builder*) clearHasNew;

- (BOOL) hasMsg;
- (NSString*) msg;
- (MChatIndex_Builder*) setMsg:(NSString*) value;
- (MChatIndex_Builder*) clearMsg;

- (BOOL) hasTime;
- (NSString*) time;
- (MChatIndex_Builder*) setTime:(NSString*) value;
- (MChatIndex_Builder*) clearTime;

- (BOOL) hasTopicid;
- (NSString*) topicid;
- (MChatIndex_Builder*) setTopicid:(NSString*) value;
- (MChatIndex_Builder*) clearTopicid;

- (BOOL) hasTopicImg;
- (NSString*) topicImg;
- (MChatIndex_Builder*) setTopicImg:(NSString*) value;
- (MChatIndex_Builder*) clearTopicImg;

- (BOOL) hasTopicContent;
- (NSString*) topicContent;
- (MChatIndex_Builder*) setTopicContent:(NSString*) value;
- (MChatIndex_Builder*) clearTopicContent;
@end

@interface MChats : PBGeneratedMessage {
@private
  BOOL hasHeadImg_:1;
  BOOL hasTargetid_:1;
  BOOL hasPushId_:1;
  int32_t headImg;
  NSString* targetid;
  NSString* pushId;
  NSMutableArray* mutableChatList;
}
- (BOOL) hasTargetid;
- (BOOL) hasHeadImg;
- (BOOL) hasPushId;
@property (readonly, retain) NSString* targetid;
@property (readonly) int32_t headImg;
@property (readonly, retain) NSString* pushId;
- (NSArray*) chatList;
- (MChat*) chatAtIndex:(int32_t) index;

+ (MChats*) defaultInstance;
- (MChats*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MChats_Builder*) builder;
+ (MChats_Builder*) builder;
+ (MChats_Builder*) builderWithPrototype:(MChats*) prototype;

+ (MChats*) parseFromData:(NSData*) data;
+ (MChats*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MChats*) parseFromInputStream:(NSInputStream*) input;
+ (MChats*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MChats*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MChats*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MChats_Builder : PBGeneratedMessage_Builder {
@private
  MChats* result;
}

- (MChats*) defaultInstance;

- (MChats_Builder*) clear;
- (MChats_Builder*) clone;

- (MChats*) build;
- (MChats*) buildPartial;

- (MChats_Builder*) mergeFrom:(MChats*) other;
- (MChats_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MChats_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) chatList;
- (MChat*) chatAtIndex:(int32_t) index;
- (MChats_Builder*) replaceChatAtIndex:(int32_t) index with:(MChat*) value;
- (MChats_Builder*) addChat:(MChat*) value;
- (MChats_Builder*) addAllChat:(NSArray*) values;
- (MChats_Builder*) clearChatList;

- (BOOL) hasTargetid;
- (NSString*) targetid;
- (MChats_Builder*) setTargetid:(NSString*) value;
- (MChats_Builder*) clearTargetid;

- (BOOL) hasHeadImg;
- (int32_t) headImg;
- (MChats_Builder*) setHeadImg:(int32_t) value;
- (MChats_Builder*) clearHeadImg;

- (BOOL) hasPushId;
- (NSString*) pushId;
- (MChats_Builder*) setPushId:(NSString*) value;
- (MChats_Builder*) clearPushId;
@end

@interface MChat : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasUserid_:1;
  BOOL hasContent_:1;
  BOOL hasImg_:1;
  BOOL hasTime_:1;
  BOOL hasCreatetime_:1;
  BOOL hasSize_:1;
  NSString* id;
  NSString* userid;
  NSString* content;
  NSString* img;
  NSString* time;
  NSString* createtime;
  NSString* size;
}
- (BOOL) hasId;
- (BOOL) hasUserid;
- (BOOL) hasContent;
- (BOOL) hasImg;
- (BOOL) hasTime;
- (BOOL) hasCreatetime;
- (BOOL) hasSize;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* userid;
@property (readonly, retain) NSString* content;
@property (readonly, retain) NSString* img;
@property (readonly, retain) NSString* time;
@property (readonly, retain) NSString* createtime;
@property (readonly, retain) NSString* size;

+ (MChat*) defaultInstance;
- (MChat*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MChat_Builder*) builder;
+ (MChat_Builder*) builder;
+ (MChat_Builder*) builderWithPrototype:(MChat*) prototype;

+ (MChat*) parseFromData:(NSData*) data;
+ (MChat*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MChat*) parseFromInputStream:(NSInputStream*) input;
+ (MChat*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MChat*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MChat*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MChat_Builder : PBGeneratedMessage_Builder {
@private
  MChat* result;
}

- (MChat*) defaultInstance;

- (MChat_Builder*) clear;
- (MChat_Builder*) clone;

- (MChat*) build;
- (MChat*) buildPartial;

- (MChat_Builder*) mergeFrom:(MChat*) other;
- (MChat_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MChat_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (MChat_Builder*) setId:(NSString*) value;
- (MChat_Builder*) clearId;

- (BOOL) hasUserid;
- (NSString*) userid;
- (MChat_Builder*) setUserid:(NSString*) value;
- (MChat_Builder*) clearUserid;

- (BOOL) hasContent;
- (NSString*) content;
- (MChat_Builder*) setContent:(NSString*) value;
- (MChat_Builder*) clearContent;

- (BOOL) hasImg;
- (NSString*) img;
- (MChat_Builder*) setImg:(NSString*) value;
- (MChat_Builder*) clearImg;

- (BOOL) hasTime;
- (NSString*) time;
- (MChat_Builder*) setTime:(NSString*) value;
- (MChat_Builder*) clearTime;

- (BOOL) hasCreatetime;
- (NSString*) createtime;
- (MChat_Builder*) setCreatetime:(NSString*) value;
- (MChat_Builder*) clearCreatetime;

- (BOOL) hasSize;
- (NSString*) size;
- (MChat_Builder*) setSize:(NSString*) value;
- (MChat_Builder*) clearSize;
@end

@interface MView : PBGeneratedMessage {
@private
  BOOL hasHeadImg_:1;
  BOOL hasTargetHeadImg_:1;
  BOOL hasUserid_:1;
  BOOL hasTargetid_:1;
  BOOL hasTopicid_:1;
  int32_t headImg;
  int32_t targetHeadImg;
  NSString* userid;
  NSString* targetid;
  NSString* topicid;
}
- (BOOL) hasUserid;
- (BOOL) hasHeadImg;
- (BOOL) hasTargetid;
- (BOOL) hasTargetHeadImg;
- (BOOL) hasTopicid;
@property (readonly, retain) NSString* userid;
@property (readonly) int32_t headImg;
@property (readonly, retain) NSString* targetid;
@property (readonly) int32_t targetHeadImg;
@property (readonly, retain) NSString* topicid;

+ (MView*) defaultInstance;
- (MView*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MView_Builder*) builder;
+ (MView_Builder*) builder;
+ (MView_Builder*) builderWithPrototype:(MView*) prototype;

+ (MView*) parseFromData:(NSData*) data;
+ (MView*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MView*) parseFromInputStream:(NSInputStream*) input;
+ (MView*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MView*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MView*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MView_Builder : PBGeneratedMessage_Builder {
@private
  MView* result;
}

- (MView*) defaultInstance;

- (MView_Builder*) clear;
- (MView_Builder*) clone;

- (MView*) build;
- (MView*) buildPartial;

- (MView_Builder*) mergeFrom:(MView*) other;
- (MView_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MView_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserid;
- (NSString*) userid;
- (MView_Builder*) setUserid:(NSString*) value;
- (MView_Builder*) clearUserid;

- (BOOL) hasHeadImg;
- (int32_t) headImg;
- (MView_Builder*) setHeadImg:(int32_t) value;
- (MView_Builder*) clearHeadImg;

- (BOOL) hasTargetid;
- (NSString*) targetid;
- (MView_Builder*) setTargetid:(NSString*) value;
- (MView_Builder*) clearTargetid;

- (BOOL) hasTargetHeadImg;
- (int32_t) targetHeadImg;
- (MView_Builder*) setTargetHeadImg:(int32_t) value;
- (MView_Builder*) clearTargetHeadImg;

- (BOOL) hasTopicid;
- (NSString*) topicid;
- (MView_Builder*) setTopicid:(NSString*) value;
- (MView_Builder*) clearTopicid;
@end

