// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class MMyRss;
@class MMyRssList;
@class MMyRssList_Builder;
@class MMyRss_Builder;
@class MNews;
@class MNewsList;
@class MNewsList_Builder;
@class MNews_Builder;
@class MRss;
@class MRssList;
@class MRssList_Builder;
@class MRss_Builder;

@interface ZsndNewsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface MNewsList : PBGeneratedMessage {
@private
  NSMutableArray* mutableNewsList;
}
- (NSArray*) newsList;
- (MNews*) newsAtIndex:(int32_t) index;

+ (MNewsList*) defaultInstance;
- (MNewsList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MNewsList_Builder*) builder;
+ (MNewsList_Builder*) builder;
+ (MNewsList_Builder*) builderWithPrototype:(MNewsList*) prototype;

+ (MNewsList*) parseFromData:(NSData*) data;
+ (MNewsList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MNewsList*) parseFromInputStream:(NSInputStream*) input;
+ (MNewsList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MNewsList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MNewsList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MNewsList_Builder : PBGeneratedMessage_Builder {
@private
  MNewsList* result;
}

- (MNewsList*) defaultInstance;

- (MNewsList_Builder*) clear;
- (MNewsList_Builder*) clone;

- (MNewsList*) build;
- (MNewsList*) buildPartial;

- (MNewsList_Builder*) mergeFrom:(MNewsList*) other;
- (MNewsList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MNewsList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) newsList;
- (MNews*) newsAtIndex:(int32_t) index;
- (MNewsList_Builder*) replaceNewsAtIndex:(int32_t) index with:(MNews*) value;
- (MNewsList_Builder*) addNews:(MNews*) value;
- (MNewsList_Builder*) addAllNews:(NSArray*) values;
- (MNewsList_Builder*) clearNewsList;
@end

@interface MNews : PBGeneratedMessage {
@private
  BOOL hasComment_:1;
  BOOL hasId_:1;
  BOOL hasImg_:1;
  BOOL hasSource_:1;
  BOOL hasTitle_:1;
  BOOL hasContent_:1;
  BOOL hasTime_:1;
  BOOL hasUrl_:1;
  BOOL hasAuthor_:1;
  int32_t comment;
  NSString* id;
  NSString* img;
  NSString* source;
  NSString* title;
  NSString* content;
  NSString* time;
  NSString* url;
  NSString* author;
}
- (BOOL) hasId;
- (BOOL) hasImg;
- (BOOL) hasSource;
- (BOOL) hasTitle;
- (BOOL) hasContent;
- (BOOL) hasTime;
- (BOOL) hasUrl;
- (BOOL) hasAuthor;
- (BOOL) hasComment;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* img;
@property (readonly, retain) NSString* source;
@property (readonly, retain) NSString* title;
@property (readonly, retain) NSString* content;
@property (readonly, retain) NSString* time;
@property (readonly, retain) NSString* url;
@property (readonly, retain) NSString* author;
@property (readonly) int32_t comment;

+ (MNews*) defaultInstance;
- (MNews*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MNews_Builder*) builder;
+ (MNews_Builder*) builder;
+ (MNews_Builder*) builderWithPrototype:(MNews*) prototype;

+ (MNews*) parseFromData:(NSData*) data;
+ (MNews*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MNews*) parseFromInputStream:(NSInputStream*) input;
+ (MNews*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MNews*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MNews*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MNews_Builder : PBGeneratedMessage_Builder {
@private
  MNews* result;
}

- (MNews*) defaultInstance;

- (MNews_Builder*) clear;
- (MNews_Builder*) clone;

- (MNews*) build;
- (MNews*) buildPartial;

- (MNews_Builder*) mergeFrom:(MNews*) other;
- (MNews_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MNews_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (MNews_Builder*) setId:(NSString*) value;
- (MNews_Builder*) clearId;

- (BOOL) hasImg;
- (NSString*) img;
- (MNews_Builder*) setImg:(NSString*) value;
- (MNews_Builder*) clearImg;

- (BOOL) hasSource;
- (NSString*) source;
- (MNews_Builder*) setSource:(NSString*) value;
- (MNews_Builder*) clearSource;

- (BOOL) hasTitle;
- (NSString*) title;
- (MNews_Builder*) setTitle:(NSString*) value;
- (MNews_Builder*) clearTitle;

- (BOOL) hasContent;
- (NSString*) content;
- (MNews_Builder*) setContent:(NSString*) value;
- (MNews_Builder*) clearContent;

- (BOOL) hasTime;
- (NSString*) time;
- (MNews_Builder*) setTime:(NSString*) value;
- (MNews_Builder*) clearTime;

- (BOOL) hasUrl;
- (NSString*) url;
- (MNews_Builder*) setUrl:(NSString*) value;
- (MNews_Builder*) clearUrl;

- (BOOL) hasAuthor;
- (NSString*) author;
- (MNews_Builder*) setAuthor:(NSString*) value;
- (MNews_Builder*) clearAuthor;

- (BOOL) hasComment;
- (int32_t) comment;
- (MNews_Builder*) setComment:(int32_t) value;
- (MNews_Builder*) clearComment;
@end

@interface MRssList : PBGeneratedMessage {
@private
  NSMutableArray* mutableListList;
}
- (NSArray*) listList;
- (MRss*) listAtIndex:(int32_t) index;

+ (MRssList*) defaultInstance;
- (MRssList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MRssList_Builder*) builder;
+ (MRssList_Builder*) builder;
+ (MRssList_Builder*) builderWithPrototype:(MRssList*) prototype;

+ (MRssList*) parseFromData:(NSData*) data;
+ (MRssList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MRssList*) parseFromInputStream:(NSInputStream*) input;
+ (MRssList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MRssList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MRssList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MRssList_Builder : PBGeneratedMessage_Builder {
@private
  MRssList* result;
}

- (MRssList*) defaultInstance;

- (MRssList_Builder*) clear;
- (MRssList_Builder*) clone;

- (MRssList*) build;
- (MRssList*) buildPartial;

- (MRssList_Builder*) mergeFrom:(MRssList*) other;
- (MRssList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MRssList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) listList;
- (MRss*) listAtIndex:(int32_t) index;
- (MRssList_Builder*) replaceListAtIndex:(int32_t) index with:(MRss*) value;
- (MRssList_Builder*) addList:(MRss*) value;
- (MRssList_Builder*) addAllList:(NSArray*) values;
- (MRssList_Builder*) clearListList;
@end

@interface MRss : PBGeneratedMessage {
@private
  BOOL hasState_:1;
  BOOL hasCount_:1;
  BOOL hasId_:1;
  BOOL hasImg_:1;
  BOOL hasTitle_:1;
  BOOL hasContent_:1;
  int32_t state;
  int32_t count;
  NSString* id;
  NSString* img;
  NSString* title;
  NSString* content;
}
- (BOOL) hasId;
- (BOOL) hasImg;
- (BOOL) hasTitle;
- (BOOL) hasContent;
- (BOOL) hasState;
- (BOOL) hasCount;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* img;
@property (readonly, retain) NSString* title;
@property (readonly, retain) NSString* content;
@property (readonly) int32_t state;
@property (readonly) int32_t count;

+ (MRss*) defaultInstance;
- (MRss*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MRss_Builder*) builder;
+ (MRss_Builder*) builder;
+ (MRss_Builder*) builderWithPrototype:(MRss*) prototype;

+ (MRss*) parseFromData:(NSData*) data;
+ (MRss*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MRss*) parseFromInputStream:(NSInputStream*) input;
+ (MRss*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MRss*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MRss*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MRss_Builder : PBGeneratedMessage_Builder {
@private
  MRss* result;
}

- (MRss*) defaultInstance;

- (MRss_Builder*) clear;
- (MRss_Builder*) clone;

- (MRss*) build;
- (MRss*) buildPartial;

- (MRss_Builder*) mergeFrom:(MRss*) other;
- (MRss_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MRss_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (MRss_Builder*) setId:(NSString*) value;
- (MRss_Builder*) clearId;

- (BOOL) hasImg;
- (NSString*) img;
- (MRss_Builder*) setImg:(NSString*) value;
- (MRss_Builder*) clearImg;

- (BOOL) hasTitle;
- (NSString*) title;
- (MRss_Builder*) setTitle:(NSString*) value;
- (MRss_Builder*) clearTitle;

- (BOOL) hasContent;
- (NSString*) content;
- (MRss_Builder*) setContent:(NSString*) value;
- (MRss_Builder*) clearContent;

- (BOOL) hasState;
- (int32_t) state;
- (MRss_Builder*) setState:(int32_t) value;
- (MRss_Builder*) clearState;

- (BOOL) hasCount;
- (int32_t) count;
- (MRss_Builder*) setCount:(int32_t) value;
- (MRss_Builder*) clearCount;
@end

@interface MMyRssList : PBGeneratedMessage {
@private
  NSMutableArray* mutableListList;
}
- (NSArray*) listList;
- (MMyRss*) listAtIndex:(int32_t) index;

+ (MMyRssList*) defaultInstance;
- (MMyRssList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MMyRssList_Builder*) builder;
+ (MMyRssList_Builder*) builder;
+ (MMyRssList_Builder*) builderWithPrototype:(MMyRssList*) prototype;

+ (MMyRssList*) parseFromData:(NSData*) data;
+ (MMyRssList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMyRssList*) parseFromInputStream:(NSInputStream*) input;
+ (MMyRssList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMyRssList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MMyRssList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MMyRssList_Builder : PBGeneratedMessage_Builder {
@private
  MMyRssList* result;
}

- (MMyRssList*) defaultInstance;

- (MMyRssList_Builder*) clear;
- (MMyRssList_Builder*) clone;

- (MMyRssList*) build;
- (MMyRssList*) buildPartial;

- (MMyRssList_Builder*) mergeFrom:(MMyRssList*) other;
- (MMyRssList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MMyRssList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) listList;
- (MMyRss*) listAtIndex:(int32_t) index;
- (MMyRssList_Builder*) replaceListAtIndex:(int32_t) index with:(MMyRss*) value;
- (MMyRssList_Builder*) addList:(MMyRss*) value;
- (MMyRssList_Builder*) addAllList:(NSArray*) values;
- (MMyRssList_Builder*) clearListList;
@end

@interface MMyRss : PBGeneratedMessage {
@private
  BOOL hasCount_:1;
  BOOL hasId_:1;
  BOOL hasTitle_:1;
  int32_t count;
  NSString* id;
  NSString* title;
  NSMutableArray* mutableNewsList;
}
- (BOOL) hasId;
- (BOOL) hasTitle;
- (BOOL) hasCount;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* title;
@property (readonly) int32_t count;
- (NSArray*) newsList;
- (MNews*) newsAtIndex:(int32_t) index;

+ (MMyRss*) defaultInstance;
- (MMyRss*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MMyRss_Builder*) builder;
+ (MMyRss_Builder*) builder;
+ (MMyRss_Builder*) builderWithPrototype:(MMyRss*) prototype;

+ (MMyRss*) parseFromData:(NSData*) data;
+ (MMyRss*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMyRss*) parseFromInputStream:(NSInputStream*) input;
+ (MMyRss*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMyRss*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MMyRss*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MMyRss_Builder : PBGeneratedMessage_Builder {
@private
  MMyRss* result;
}

- (MMyRss*) defaultInstance;

- (MMyRss_Builder*) clear;
- (MMyRss_Builder*) clone;

- (MMyRss*) build;
- (MMyRss*) buildPartial;

- (MMyRss_Builder*) mergeFrom:(MMyRss*) other;
- (MMyRss_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MMyRss_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (MMyRss_Builder*) setId:(NSString*) value;
- (MMyRss_Builder*) clearId;

- (BOOL) hasTitle;
- (NSString*) title;
- (MMyRss_Builder*) setTitle:(NSString*) value;
- (MMyRss_Builder*) clearTitle;

- (NSArray*) newsList;
- (MNews*) newsAtIndex:(int32_t) index;
- (MMyRss_Builder*) replaceNewsAtIndex:(int32_t) index with:(MNews*) value;
- (MMyRss_Builder*) addNews:(MNews*) value;
- (MMyRss_Builder*) addAllNews:(NSArray*) values;
- (MMyRss_Builder*) clearNewsList;

- (BOOL) hasCount;
- (int32_t) count;
- (MMyRss_Builder*) setCount:(int32_t) value;
- (MMyRss_Builder*) clearCount;
@end

