// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class MAddMarket;
@class MAddMarket_Builder;
@class MMarketList;
@class MMarketList_Builder;
@class MMarketType;
@class MMarketTypeList;
@class MMarketTypeList_Builder;
@class MMarketType_Builder;
@class MProduct;
@class MProduct_Builder;

@interface ZsndMarketRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface MMarketType : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  NSString* id;
}
- (BOOL) hasId;
@property (readonly, retain) NSString* id;

+ (MMarketType*) defaultInstance;
- (MMarketType*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MMarketType_Builder*) builder;
+ (MMarketType_Builder*) builder;
+ (MMarketType_Builder*) builderWithPrototype:(MMarketType*) prototype;

+ (MMarketType*) parseFromData:(NSData*) data;
+ (MMarketType*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMarketType*) parseFromInputStream:(NSInputStream*) input;
+ (MMarketType*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMarketType*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MMarketType*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MMarketType_Builder : PBGeneratedMessage_Builder {
@private
  MMarketType* result;
}

- (MMarketType*) defaultInstance;

- (MMarketType_Builder*) clear;
- (MMarketType_Builder*) clone;

- (MMarketType*) build;
- (MMarketType*) buildPartial;

- (MMarketType_Builder*) mergeFrom:(MMarketType*) other;
- (MMarketType_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MMarketType_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (MMarketType_Builder*) setId:(NSString*) value;
- (MMarketType_Builder*) clearId;
@end

@interface MMarketTypeList : PBGeneratedMessage {
@private
  NSMutableArray* mutableMarketList;
}
- (NSArray*) marketList;
- (MMarketType*) marketAtIndex:(int32_t) index;

+ (MMarketTypeList*) defaultInstance;
- (MMarketTypeList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MMarketTypeList_Builder*) builder;
+ (MMarketTypeList_Builder*) builder;
+ (MMarketTypeList_Builder*) builderWithPrototype:(MMarketTypeList*) prototype;

+ (MMarketTypeList*) parseFromData:(NSData*) data;
+ (MMarketTypeList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMarketTypeList*) parseFromInputStream:(NSInputStream*) input;
+ (MMarketTypeList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMarketTypeList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MMarketTypeList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MMarketTypeList_Builder : PBGeneratedMessage_Builder {
@private
  MMarketTypeList* result;
}

- (MMarketTypeList*) defaultInstance;

- (MMarketTypeList_Builder*) clear;
- (MMarketTypeList_Builder*) clone;

- (MMarketTypeList*) build;
- (MMarketTypeList*) buildPartial;

- (MMarketTypeList_Builder*) mergeFrom:(MMarketTypeList*) other;
- (MMarketTypeList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MMarketTypeList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) marketList;
- (MMarketType*) marketAtIndex:(int32_t) index;
- (MMarketTypeList_Builder*) replaceMarketAtIndex:(int32_t) index with:(MMarketType*) value;
- (MMarketTypeList_Builder*) addMarket:(MMarketType*) value;
- (MMarketTypeList_Builder*) addAllMarket:(NSArray*) values;
- (MMarketTypeList_Builder*) clearMarketList;
@end

@interface MProduct : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  NSString* id;
}
- (BOOL) hasId;
@property (readonly, retain) NSString* id;

+ (MProduct*) defaultInstance;
- (MProduct*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MProduct_Builder*) builder;
+ (MProduct_Builder*) builder;
+ (MProduct_Builder*) builderWithPrototype:(MProduct*) prototype;

+ (MProduct*) parseFromData:(NSData*) data;
+ (MProduct*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MProduct*) parseFromInputStream:(NSInputStream*) input;
+ (MProduct*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MProduct*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MProduct*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MProduct_Builder : PBGeneratedMessage_Builder {
@private
  MProduct* result;
}

- (MProduct*) defaultInstance;

- (MProduct_Builder*) clear;
- (MProduct_Builder*) clone;

- (MProduct*) build;
- (MProduct*) buildPartial;

- (MProduct_Builder*) mergeFrom:(MProduct*) other;
- (MProduct_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MProduct_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (MProduct_Builder*) setId:(NSString*) value;
- (MProduct_Builder*) clearId;
@end

@interface MMarketList : PBGeneratedMessage {
@private
  NSMutableArray* mutableMarketList;
}
- (NSArray*) marketList;
- (MProduct*) marketAtIndex:(int32_t) index;

+ (MMarketList*) defaultInstance;
- (MMarketList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MMarketList_Builder*) builder;
+ (MMarketList_Builder*) builder;
+ (MMarketList_Builder*) builderWithPrototype:(MMarketList*) prototype;

+ (MMarketList*) parseFromData:(NSData*) data;
+ (MMarketList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMarketList*) parseFromInputStream:(NSInputStream*) input;
+ (MMarketList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMarketList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MMarketList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MMarketList_Builder : PBGeneratedMessage_Builder {
@private
  MMarketList* result;
}

- (MMarketList*) defaultInstance;

- (MMarketList_Builder*) clear;
- (MMarketList_Builder*) clone;

- (MMarketList*) build;
- (MMarketList*) buildPartial;

- (MMarketList_Builder*) mergeFrom:(MMarketList*) other;
- (MMarketList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MMarketList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) marketList;
- (MProduct*) marketAtIndex:(int32_t) index;
- (MMarketList_Builder*) replaceMarketAtIndex:(int32_t) index with:(MProduct*) value;
- (MMarketList_Builder*) addMarket:(MProduct*) value;
- (MMarketList_Builder*) addAllMarket:(NSArray*) values;
- (MMarketList_Builder*) clearMarketList;
@end

@interface MAddMarket : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  NSString* name;
}
- (BOOL) hasName;
@property (readonly, retain) NSString* name;

+ (MAddMarket*) defaultInstance;
- (MAddMarket*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MAddMarket_Builder*) builder;
+ (MAddMarket_Builder*) builder;
+ (MAddMarket_Builder*) builderWithPrototype:(MAddMarket*) prototype;

+ (MAddMarket*) parseFromData:(NSData*) data;
+ (MAddMarket*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MAddMarket*) parseFromInputStream:(NSInputStream*) input;
+ (MAddMarket*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MAddMarket*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MAddMarket*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MAddMarket_Builder : PBGeneratedMessage_Builder {
@private
  MAddMarket* result;
}

- (MAddMarket*) defaultInstance;

- (MAddMarket_Builder*) clear;
- (MAddMarket_Builder*) clone;

- (MAddMarket*) build;
- (MAddMarket*) buildPartial;

- (MAddMarket_Builder*) mergeFrom:(MAddMarket*) other;
- (MAddMarket_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MAddMarket_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (MAddMarket_Builder*) setName:(NSString*) value;
- (MAddMarket_Builder*) clearName;
@end

