// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class MUser;
@class MUser_Builder;

@interface ZsndUserRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface MUser : PBGeneratedMessage {
@private
  BOOL hasSex_:1;
  BOOL hasFlower_:1;
  BOOL hasIsV_:1;
  BOOL hasId_:1;
  BOOL hasAccount_:1;
  BOOL hasHeadImg_:1;
  BOOL hasNickname_:1;
  BOOL hasVerify_:1;
  BOOL hasBirthday_:1;
  BOOL hasBelong_:1;
  int32_t sex;
  int32_t flower;
  int32_t isV;
  NSString* id;
  NSString* account;
  NSString* headImg;
  NSString* nickname;
  NSString* verify;
  NSString* birthday;
  NSString* belong;
  NSMutableArray* mutableTagsList;
}
- (BOOL) hasId;
- (BOOL) hasAccount;
- (BOOL) hasHeadImg;
- (BOOL) hasNickname;
- (BOOL) hasVerify;
- (BOOL) hasSex;
- (BOOL) hasBirthday;
- (BOOL) hasFlower;
- (BOOL) hasBelong;
- (BOOL) hasIsV;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* account;
@property (readonly, retain) NSString* headImg;
@property (readonly, retain) NSString* nickname;
@property (readonly, retain) NSString* verify;
@property (readonly) int32_t sex;
@property (readonly, retain) NSString* birthday;
@property (readonly) int32_t flower;
@property (readonly, retain) NSString* belong;
@property (readonly) int32_t isV;
- (NSArray*) tagsList;
- (NSString*) tagsAtIndex:(int32_t) index;

+ (MUser*) defaultInstance;
- (MUser*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MUser_Builder*) builder;
+ (MUser_Builder*) builder;
+ (MUser_Builder*) builderWithPrototype:(MUser*) prototype;

+ (MUser*) parseFromData:(NSData*) data;
+ (MUser*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MUser*) parseFromInputStream:(NSInputStream*) input;
+ (MUser*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MUser*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MUser*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MUser_Builder : PBGeneratedMessage_Builder {
@private
  MUser* result;
}

- (MUser*) defaultInstance;

- (MUser_Builder*) clear;
- (MUser_Builder*) clone;

- (MUser*) build;
- (MUser*) buildPartial;

- (MUser_Builder*) mergeFrom:(MUser*) other;
- (MUser_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MUser_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (MUser_Builder*) setId:(NSString*) value;
- (MUser_Builder*) clearId;

- (BOOL) hasAccount;
- (NSString*) account;
- (MUser_Builder*) setAccount:(NSString*) value;
- (MUser_Builder*) clearAccount;

- (BOOL) hasHeadImg;
- (NSString*) headImg;
- (MUser_Builder*) setHeadImg:(NSString*) value;
- (MUser_Builder*) clearHeadImg;

- (BOOL) hasNickname;
- (NSString*) nickname;
- (MUser_Builder*) setNickname:(NSString*) value;
- (MUser_Builder*) clearNickname;

- (BOOL) hasVerify;
- (NSString*) verify;
- (MUser_Builder*) setVerify:(NSString*) value;
- (MUser_Builder*) clearVerify;

- (BOOL) hasSex;
- (int32_t) sex;
- (MUser_Builder*) setSex:(int32_t) value;
- (MUser_Builder*) clearSex;

- (BOOL) hasBirthday;
- (NSString*) birthday;
- (MUser_Builder*) setBirthday:(NSString*) value;
- (MUser_Builder*) clearBirthday;

- (NSArray*) tagsList;
- (NSString*) tagsAtIndex:(int32_t) index;
- (MUser_Builder*) replaceTagsAtIndex:(int32_t) index with:(NSString*) value;
- (MUser_Builder*) addTags:(NSString*) value;
- (MUser_Builder*) addAllTags:(NSArray*) values;
- (MUser_Builder*) clearTagsList;

- (BOOL) hasFlower;
- (int32_t) flower;
- (MUser_Builder*) setFlower:(int32_t) value;
- (MUser_Builder*) clearFlower;

- (BOOL) hasBelong;
- (NSString*) belong;
- (MUser_Builder*) setBelong:(NSString*) value;
- (MUser_Builder*) clearBelong;

- (BOOL) hasIsV;
- (int32_t) isV;
- (MUser_Builder*) setIsV:(int32_t) value;
- (MUser_Builder*) clearIsV;
@end

