// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class MAddLostOrFound;
@class MAddLostOrFound_Builder;
@class MLostAndFound;
@class MLostAndFoundList;
@class MLostAndFoundList_Builder;
@class MLostAndFound_Builder;

@interface ZsndLostRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface MLostAndFoundList : PBGeneratedMessage {
@private
  NSMutableArray* mutableLfList;
}
- (NSArray*) lfList;
- (MLostAndFound*) lfAtIndex:(int32_t) index;

+ (MLostAndFoundList*) defaultInstance;
- (MLostAndFoundList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MLostAndFoundList_Builder*) builder;
+ (MLostAndFoundList_Builder*) builder;
+ (MLostAndFoundList_Builder*) builderWithPrototype:(MLostAndFoundList*) prototype;

+ (MLostAndFoundList*) parseFromData:(NSData*) data;
+ (MLostAndFoundList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MLostAndFoundList*) parseFromInputStream:(NSInputStream*) input;
+ (MLostAndFoundList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MLostAndFoundList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MLostAndFoundList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MLostAndFoundList_Builder : PBGeneratedMessage_Builder {
@private
  MLostAndFoundList* result;
}

- (MLostAndFoundList*) defaultInstance;

- (MLostAndFoundList_Builder*) clear;
- (MLostAndFoundList_Builder*) clone;

- (MLostAndFoundList*) build;
- (MLostAndFoundList*) buildPartial;

- (MLostAndFoundList_Builder*) mergeFrom:(MLostAndFoundList*) other;
- (MLostAndFoundList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MLostAndFoundList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) lfList;
- (MLostAndFound*) lfAtIndex:(int32_t) index;
- (MLostAndFoundList_Builder*) replaceLfAtIndex:(int32_t) index with:(MLostAndFound*) value;
- (MLostAndFoundList_Builder*) addLf:(MLostAndFound*) value;
- (MLostAndFoundList_Builder*) addAllLf:(NSArray*) values;
- (MLostAndFoundList_Builder*) clearLfList;
@end

@interface MLostAndFound : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasAddress_:1;
  BOOL hasDesc_:1;
  BOOL hasUserid_:1;
  BOOL hasNickname_:1;
  BOOL hasContact_:1;
  BOOL hasTime_:1;
  NSString* id;
  NSString* address;
  NSString* desc;
  NSString* userid;
  NSString* nickname;
  NSString* contact;
  NSString* time;
  NSMutableArray* mutableImgList;
}
- (BOOL) hasId;
- (BOOL) hasAddress;
- (BOOL) hasDesc;
- (BOOL) hasUserid;
- (BOOL) hasNickname;
- (BOOL) hasContact;
- (BOOL) hasTime;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* address;
@property (readonly, retain) NSString* desc;
@property (readonly, retain) NSString* userid;
@property (readonly, retain) NSString* nickname;
@property (readonly, retain) NSString* contact;
@property (readonly, retain) NSString* time;
- (NSArray*) imgList;
- (NSString*) imgAtIndex:(int32_t) index;

+ (MLostAndFound*) defaultInstance;
- (MLostAndFound*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MLostAndFound_Builder*) builder;
+ (MLostAndFound_Builder*) builder;
+ (MLostAndFound_Builder*) builderWithPrototype:(MLostAndFound*) prototype;

+ (MLostAndFound*) parseFromData:(NSData*) data;
+ (MLostAndFound*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MLostAndFound*) parseFromInputStream:(NSInputStream*) input;
+ (MLostAndFound*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MLostAndFound*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MLostAndFound*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MLostAndFound_Builder : PBGeneratedMessage_Builder {
@private
  MLostAndFound* result;
}

- (MLostAndFound*) defaultInstance;

- (MLostAndFound_Builder*) clear;
- (MLostAndFound_Builder*) clone;

- (MLostAndFound*) build;
- (MLostAndFound*) buildPartial;

- (MLostAndFound_Builder*) mergeFrom:(MLostAndFound*) other;
- (MLostAndFound_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MLostAndFound_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (MLostAndFound_Builder*) setId:(NSString*) value;
- (MLostAndFound_Builder*) clearId;

- (BOOL) hasAddress;
- (NSString*) address;
- (MLostAndFound_Builder*) setAddress:(NSString*) value;
- (MLostAndFound_Builder*) clearAddress;

- (BOOL) hasDesc;
- (NSString*) desc;
- (MLostAndFound_Builder*) setDesc:(NSString*) value;
- (MLostAndFound_Builder*) clearDesc;

- (BOOL) hasUserid;
- (NSString*) userid;
- (MLostAndFound_Builder*) setUserid:(NSString*) value;
- (MLostAndFound_Builder*) clearUserid;

- (BOOL) hasNickname;
- (NSString*) nickname;
- (MLostAndFound_Builder*) setNickname:(NSString*) value;
- (MLostAndFound_Builder*) clearNickname;

- (BOOL) hasContact;
- (NSString*) contact;
- (MLostAndFound_Builder*) setContact:(NSString*) value;
- (MLostAndFound_Builder*) clearContact;

- (BOOL) hasTime;
- (NSString*) time;
- (MLostAndFound_Builder*) setTime:(NSString*) value;
- (MLostAndFound_Builder*) clearTime;

- (NSArray*) imgList;
- (NSString*) imgAtIndex:(int32_t) index;
- (MLostAndFound_Builder*) replaceImgAtIndex:(int32_t) index with:(NSString*) value;
- (MLostAndFound_Builder*) addImg:(NSString*) value;
- (MLostAndFound_Builder*) addAllImg:(NSArray*) values;
- (MLostAndFound_Builder*) clearImgList;
@end

@interface MAddLostOrFound : PBGeneratedMessage {
@private
  BOOL hasType_:1;
  BOOL hasAddress_:1;
  BOOL hasDesc_:1;
  BOOL hasContact_:1;
  BOOL hasTime_:1;
  BOOL hasImg1_:1;
  BOOL hasImg2_:1;
  BOOL hasImg3_:1;
  BOOL hasImg4_:1;
  int32_t type;
  NSString* address;
  NSString* desc;
  NSString* contact;
  NSString* time;
  NSData* img1;
  NSData* img2;
  NSData* img3;
  NSData* img4;
}
- (BOOL) hasType;
- (BOOL) hasAddress;
- (BOOL) hasDesc;
- (BOOL) hasContact;
- (BOOL) hasTime;
- (BOOL) hasImg1;
- (BOOL) hasImg2;
- (BOOL) hasImg3;
- (BOOL) hasImg4;
@property (readonly) int32_t type;
@property (readonly, retain) NSString* address;
@property (readonly, retain) NSString* desc;
@property (readonly, retain) NSString* contact;
@property (readonly, retain) NSString* time;
@property (readonly, retain) NSData* img1;
@property (readonly, retain) NSData* img2;
@property (readonly, retain) NSData* img3;
@property (readonly, retain) NSData* img4;

+ (MAddLostOrFound*) defaultInstance;
- (MAddLostOrFound*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MAddLostOrFound_Builder*) builder;
+ (MAddLostOrFound_Builder*) builder;
+ (MAddLostOrFound_Builder*) builderWithPrototype:(MAddLostOrFound*) prototype;

+ (MAddLostOrFound*) parseFromData:(NSData*) data;
+ (MAddLostOrFound*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MAddLostOrFound*) parseFromInputStream:(NSInputStream*) input;
+ (MAddLostOrFound*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MAddLostOrFound*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MAddLostOrFound*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MAddLostOrFound_Builder : PBGeneratedMessage_Builder {
@private
  MAddLostOrFound* result;
}

- (MAddLostOrFound*) defaultInstance;

- (MAddLostOrFound_Builder*) clear;
- (MAddLostOrFound_Builder*) clone;

- (MAddLostOrFound*) build;
- (MAddLostOrFound*) buildPartial;

- (MAddLostOrFound_Builder*) mergeFrom:(MAddLostOrFound*) other;
- (MAddLostOrFound_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MAddLostOrFound_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (int32_t) type;
- (MAddLostOrFound_Builder*) setType:(int32_t) value;
- (MAddLostOrFound_Builder*) clearType;

- (BOOL) hasAddress;
- (NSString*) address;
- (MAddLostOrFound_Builder*) setAddress:(NSString*) value;
- (MAddLostOrFound_Builder*) clearAddress;

- (BOOL) hasDesc;
- (NSString*) desc;
- (MAddLostOrFound_Builder*) setDesc:(NSString*) value;
- (MAddLostOrFound_Builder*) clearDesc;

- (BOOL) hasContact;
- (NSString*) contact;
- (MAddLostOrFound_Builder*) setContact:(NSString*) value;
- (MAddLostOrFound_Builder*) clearContact;

- (BOOL) hasTime;
- (NSString*) time;
- (MAddLostOrFound_Builder*) setTime:(NSString*) value;
- (MAddLostOrFound_Builder*) clearTime;

- (BOOL) hasImg1;
- (NSData*) img1;
- (MAddLostOrFound_Builder*) setImg1:(NSData*) value;
- (MAddLostOrFound_Builder*) clearImg1;

- (BOOL) hasImg2;
- (NSData*) img2;
- (MAddLostOrFound_Builder*) setImg2:(NSData*) value;
- (MAddLostOrFound_Builder*) clearImg2;

- (BOOL) hasImg3;
- (NSData*) img3;
- (MAddLostOrFound_Builder*) setImg3:(NSData*) value;
- (MAddLostOrFound_Builder*) clearImg3;

- (BOOL) hasImg4;
- (NSData*) img4;
- (MAddLostOrFound_Builder*) setImg4:(NSData*) value;
- (MAddLostOrFound_Builder*) clearImg4;
@end

